#!/bin/bash

# This is a one-liner filter script
# It reads a list of 'bad words' from a blacklist file
# and filters all filenames beneith a specified directory
# for those words and removes them.
#
# This could easily modified to enable replacing the words
# with specific replacement words. It could still remain a 
# one-liner for that, allthough it might get about 50% longer.

BLACKLIST=$(sed -e 's/#.*$//' blacklist | grep -v '^$') && find $1 -type f -exec sh -c 'f="{}"; echo "$BLACKLIST" | while IFS=":" read BAD GOOD ; do filtered=$(echo "$f" | sed -r "s/($BAD)[[:space:]]*/$GOOD/g" | sed -r "s/[[:space:]]*$//"); [ "$f" != "$filtered" ] && mv -v "$f" "$filtered" ; done' \;
